version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=nizael
      - POSTGRES_PASSWORD=valente
    ports:
      - '5436:5432'
    volumes: 
       - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
